AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LambdaTestApp - Função Lambda .NET 9

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: dotnet8
    Architectures:
      - x86_64

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - hmg
      - prod

Resources:
  LambdaTestAppFunction:
    Type: AWS::Serverless::Function
    Properties:
    # Nome da função gerado automaticamente baseado no Stage
      

      CodeUri: src/LambdaTestApp/
      Handler: LambdaTestApp::LambdaTestApp.Function::FunctionHandler
      Description: Função Lambda .NET 9 para testes automáticos
      Environment:
        Variables:
          STAGE: !Ref Stage
      Policies:
        - AWSLambda_FullAccess
      Tags:
        # Tag gerada automaticamente, igual ao que você pega da stack
        Name: !Sub "${Stage}-webhook"

Outputs:
  WebhookName:
    Description: Nome gerado automaticamente a partir do Stage
    Value: !Sub "${Stage}-webhook"
