AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LambdaTestApp - Função Lambda .NET 9

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: dotnet9
    Architectures:
      - x86_64

Resources:
  LambdaTestAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "LambdaTestApp-${Stage}"
      CodeUri: src/LambdaTestApp/
      Handler: LambdaTestApp::LambdaTestApp.Function::FunctionHandler
      Description: Função Lambda .NET 9 para testes automáticos
      Environment:
        Variables:
          STAGE: !Ref Stage
      Policies:
        - AWSLambda_FullAccess

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hmg
      - prod