pipeline {
    agent any

    stages {

        stage('Define Stage') {
            steps {
                script {
                    if (env.BRANCH_NAME == "main") {
                        STAGE = "dev"
                    } else if (env.BRANCH_NAME.startsWith("release")) {
                        STAGE = "hmg"
                    } else if (env.BRANCH_NAME == "prod" || env.BRANCH_NAME =~ /^v?\d+\.\d+\.\d+$/) {
                        STAGE = "prod"
                    } else {
                        error("Branch '${env.BRANCH_NAME}' não mapeada.")
                    }

                    STACK_NAME = "lambda-testapp-${STAGE}"

                    echo "Branch: ${env.BRANCH_NAME}"
                    echo "Stage detectada: ${STAGE}"
                    echo "Stack selecionada: ${STACK_NAME}"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    sls deploy \
                      --stage ${STAGE} \
                      --stack-name ${STACK_NAME}
                """
            }
        }
    }
}
