pipeline {
    agent any

    stages {

        stage('Detect Stage') {
            steps {
                script {
                    if (env.BRANCH_NAME == "dev") {
                        STAGE = "dev"
                    } else if (env.BRANCH_NAME == "hmg") {
                        STAGE = "hmg"
                    } else if (env.BRANCH_NAME == "prod") {
                        STAGE = "prod"
                    } else {
                        error("Branch '${env.BRANCH_NAME}' não mapeada.")
                    }

                    STACK_NAME = "lambda-testapp-${STAGE}"

                    echo "Branch detectado: ${env.BRANCH_NAME}"
                    echo "Stage definida: ${STAGE}"
                    echo "Stack usada: ${STACK_NAME}"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    sam deploy \
                      --stack-name ${STACK_NAME} \
                      --capabilities CAPABILITY_IAM \
                      --no-confirm-changeset \
                      --resolve-s3 \
                      --parameter-overrides Stage=${STAGE}
                """
            }
        }
    }
}
